Add multi-device workgroup folders and READMEs
onnx/working-groups pull request #91
Opened 2023-07-27 23:02 UTC by mk-nvidia

2023-07-28 04:33 UTC, andife approved these changes

2023-08-03 04:44 UTC, prasanthpul requested changes

2023-08-03 04:44 UTC, prasanthpul commented on multi-device/README.md
> +* TBD
need to specify the leads before this can be approved

2023-08-03 12:35 UTC, AlexandreEichenberger commented on multi-device/README.md
> +To seed discussion in the proposed WG, we have a proposal from NVIDIA that introduces a few extensions to ONNX that allow expression of multi-device capability with minor changes relative to a single
Might it be better to avoid a company name in the objective? It could be "We have proposals presented at the last roadmap" or something similar?

2023-08-31 18:05 UTC, prasanthpul approved these changes

2023-09-06 19:21 UTC, AlexandreEichenberger approved these changes
LGTM

2023-09-06 20:05 UTC, merged